### ISSUE TITLE
README example should show working code

### ISSUE THREAD

**Issue by hmlongco** [Open-Bytes/SwiftUIFormValidator#12]
The code and explanation for the first example on the README page is as follows:
```swift
  // 1 
import FormValidator

class ExampleForm: ObservableObject {
    // 2
    @Published
    var manager = FormManager(validationType: .immediate)

    // 3
    @FormField(validator: NonEmptyValidator(message: "This field is required!"))
    var firstName: String = ""
}

struct ContentView: View {
    @ObservedObject var form = ExampleForm()
    @State var isSaveDisabled = true

    var body: some View {
        Section(header: Text("Required Fields Validation")) {
            TextField("First Name", text: $form.firstName)
                    .validation(form.firstNameValidation) // WHAT IS THIS?
        }
    }
}
```
That code contains:
```
.validation(form.firstNameValidation)
```
But form.firstNameValidation does not exist in the example!

So either there's a typo and this is meant to be `.validation(form.firstName)`, or *additional* code is needed, in which case your example is misleading and it's not as "concise and simple" as it's made out to be.

The example should show working code.

**Comment by onisiforos7** [comment]
True. You can see the examples in here to figure out that this is missing right after `var fisrtname: String = ""`
`lazy var firstNameValidation = _ firstName.validation(manager: manager)`

**Comment by hmlongco** [comment]
True, but the point is that the example shown on the README should be complete and working code. 

If it's not, and if extra code is needed for each field to make it work, then that gives a false impression as to just how "simple" and concise the tool is to use.

**Comment by ShabanKamell** [comment]
Thank you for bringing the missing code to my attention. I apologize for the oversight, as it was a copy/paste error. 
I have now updated the README file and made some improvements to it as well. 
Once again, thank you for your help.
