### ISSUE TITLE
OR Validation

### ISSUE THREAD

**Issue by TiPunch69** [Open-Bytes/SwiftUIFormValidator#13]
Is there any way to create an OR validation (enter field A or field B). Currently all validators are AND conjunctions.

**Comment by ShabanKamell** [comment]
Hey, thanks for asking the question.
You can use `disableValidation` closure for applying you login as below:

```swift
    @DateFormField(message: "Date can not be in the future!")
    var birthday: Date = Date()
    lazy var birthdayValidation = _birthday.validation(
            manager: manager,
            before: Date(),
            disableValidation: {
                // You can add logic here to disable this field validation. If you return true, the field will be always valid
                // and the validation will be ignored.
                // This is useful when you need to apply OR validation (enter field A or field B).
                false
            })
```

I have updated the example https://github.com/Open-Bytes/SwiftUIFormValidator/blob/master/Example/ExampleForm.swift.

**Comment by TiPunch69** [comment]
Super, thanks. That was exactly what I needed. Could you also add this to the documentation plz for other people?
