### ISSUE TITLE
Validators require published strings, which stops Decimal validation.

### ISSUE THREAD

**Issue by JulesMoorhouse** [Open-Bytes/SwiftUIFormValidator#9]
I'm trying to validate a decimal, however all the validators require strings.... (apart from the date validator)

<img width="661" alt="image" src="https://user-images.githubusercontent.com/361024/230650853-6bac3f8b-64fb-4316-ae9f-92902567ddc5.png">

My textfield requires a decimal....

```
            TextField(
                "My text",
                value: $viewModel.amount,
                format: .currency(code: Locale.current.currencyCode ?? "")
            )
            .keyboardType(.decimalPad)
```

Could the validators be changed to use generics perhaps ?

The validators also require a published variable.

I'd like to validate the the value is positive or negative, depending on state. e.g. income or expense. 
Also that the value isn't zero.

I'm not sure how to proceed, any suggestions?

**Comment by JulesMoorhouse** [comment]
I've made a little progress... 
But I'm not sure about the `setupValidator` parameter... from the ValidationPublishers class...

```
extension Published.Publisher where Value == Decimal {
    func myNonEmptyValidator(
        form: FormValidation,
        errorMessage: @autoclosure @escaping StringProducerClosure = "",
        onValidate: OnValidate? = nil
    ) -> ValidationContainer {
        let validator = NonEmptyValidator()
        let message = errorMessage()

        return ValidationPublishers.create(
            form: form,
            validator: validator,
            for: eraseToAnyPublisher(),
            errorMessage: !message.isEmpty ? message : form.messages.required,
            onValidate: onValidate,
            setupValidator: { _ in }
        )
    }
}
```

**Comment by ShabanKamell** [comment]
Hi,

I'm working on a fix and will update you as soon as it's complete.

**Comment by ShabanKamell** [comment]
Hi,

I'm excited to announce that version `1.0.0 `of our library is now available, featuring the ability to validate any data type using property wrappers and generics.

Thanks for your feedback
